#!/bin/bash

echo -n "Enter a password : "
read -r password

LEN=${#password}

if [ "$LEN" -lt 8 ]; then
	printf "%s is smaller than 8 characters\n" "$password"
fi

if [[ "$password" == *[0-9]*  ]]; then
		:
else
	printf "%s does not contain a numeric character\n" "$password"
fi

if [[ "$password" == *[',#$%&*+-=']*  ]]; then
	:
else
	printf "%s does not contain a punctuation character\n" "$password"
fi



